const actionTypes = {
    ADD_TASK: "ADD_TASK",
    CHANGE_TEXT: "CHANGE_TEXT",
    DELETE_TASK: "DELETE_TASK",
    SET_ID: "SET_ID",
    CHANGE_TITLE_TASK: "CHANGE_TITLE_TASK",
    ADD_BODY_FOR_DESCRIPTION: "ADD_BODY_FOR_DESCRIPTION",
    CHANGE_CHECKED_fLAG: "CHANGE_CHECKED_fLAG",
    CHANGE_SELECTED_VALUE: "CHANGE_SELECTED_VALUE",
    ADD_INFO_FOR_WEATHER: "ADD_INFO_FOR_WEATHER",
    IS_LOADING: "IS_LOADING",
    INFO_WEATHER_FETCH_DATA: "INFO_WEATHER_FETCH_DATA",
};

 export default actionTypes;